       ORG 1000H
t1  dw 1,2,5,4,7
t2  dw 2,3,4,5,7
diml db ?
suma dw ?

       ORG 3000H
SUBR:  CMP CX,DX
       JS CAMBIO
EVALU: CMP CX,5
       JNS COND1
       JMP FIN
COND1: CMP CX,5
       JNZ SUMA
       JMP FIN
SUMA:  ADD suma,CX; SUMO LOS VALORES DEL PARAMETRO POR VALOR MAYORES A 5
       JMP FIN
CAMBIO:MOV [BX],CX; REEMPLAZO EL PARA. POR REFER. POR EL PARA. POR VALOR
       JMP EVALU
FIN:   RET
       
       ORG 2000H
       MOV AX, OFFSET t1; PARAMETRO POR REFERENCIA
       MOV CX, OFFSET t2; DIRECCION PARAMETRO POR VALOR
       PUSH CX
       MOV CX, t2; PARAMETRO POR VALOR
       MOV suma,0; INICIALIZO LA SUMA
       MOV diml, OFFSET t2 - OFFSET t1; GUARDO DIML DE LAS TABLAS
TABLAS:MOV BX,AX
       MOV DX,[BX]; PARAMETRO POR REFERENCIA
       CALL SUBR
       DEC diml
       JZ FIN2
       POP CX
       INC CX
       PUSH CX
       MOV BX,CX
       MOV CX,[BX]
       INC AX
       JMP TABLAS
FIN2:  HLT
       END
